name: First Workflow
on:
  workflow_dispatch:

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Printing Greeting
        run: |
          #!/bin/bash
          Add_Command="Hi"
          if [ "${{ vars.PROD_SIZE }}" == "" ]
          then
          Add_Command="NO VALUE PRESENT!!"
          elif [ "${{ vars.PROD_SIZE }}" == "custom" ]
          then
          Add_Command="$Add_Command BAKU"
          else
          Add_Command="$Add_Command Debarshi"
          fi
          echo "$Add_Command"
          echo "${{ vars.PROD_SIZE }}"

