name: First Workflow
on:
  workflow_dispatch:

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Printing Greeting
        run: |
          #!/bin/bash
          Add_Command="Hi"
          is_custom=1
          echo "-----------------------TESTING CONDITION----------------------------------------------------------------"
          list="${{ vars.PROD_SIZE }}"
          #for deploy_size in $list; do 
          if[ "${{ vars.PROD_SIZE }}" != ""]
          then
          is_custom=0
          echo is_custom
          echo deploy_size
          else
          echo is_custom
          echo deploy_size
          fi
          #done
          echo "--------------------------------------------------------------------------------------------------------"
          
          if [ "${{ vars.PROD_SIZE }}" == "" ]
          then
          Add_Command="NO VALUE PRESENT!!"
          elif [ "${{ vars.PROD_SIZE }}" == "custom" ]
          then
          Add_Command="$Add_Command BAKU"
          Add_Command="$Add_Command prod size is '${{ vars.PROD_SIZE }}'"
          else
          Add_Command="$Add_Command Debarshi"
          fi
          echo "$Add_Command"
          #echo "${{ vars.PROD_SIZE }}"

